logging.level.org.springframework.security: INFO

spring:
  redis:
    host: 127.0.0.1
    database: 0

zuul:
  routes:
    test:
      path: /**
      url: ${RESOURCE_SERVER}

server:
  port: ${PROXY_PORT}
  ssl:
    key-store: classpath:server-keystore.jks
    key-store-password: 123456
    key-alias: ServerCert_signedByCA
    trust-store: classpath:server-truststore.jks
    trust-store-password: 123456
    enabled: true
    client-auth: need